.PHONY: clean All

All:
	@echo "----------Building project:[ ex_20 - Debug ]----------"
	@cd "ex_20" && "$(MAKE)" -f  "ex_20.mk"
clean:
	@echo "----------Cleaning project:[ ex_20 - Debug ]----------"
	@cd "ex_20" && "$(MAKE)" -f  "ex_20.mk" clean
