.PHONY: clean All

All:
	@echo "----------Building project:[ ex_19 - Debug ]----------"
	@cd "ex_19" && "$(MAKE)" -f  "ex_19.mk"
clean:
	@echo "----------Cleaning project:[ ex_19 - Debug ]----------"
	@cd "ex_19" && "$(MAKE)" -f  "ex_19.mk" clean
