.PHONY: clean All

All:
	@echo "----------Building project:[ ex_28 - Debug ]----------"
	@cd "ex_28" && "$(MAKE)" -f  "ex_28.mk"
clean:
	@echo "----------Cleaning project:[ ex_28 - Debug ]----------"
	@cd "ex_28" && "$(MAKE)" -f  "ex_28.mk" clean
