.PHONY: clean All

All:
	@echo "----------Building project:[ Matrix_s - Debug ]----------"
	@cd "Matrix_s" && "$(MAKE)" -f  "Matrix_s.mk"
clean:
	@echo "----------Cleaning project:[ Matrix_s - Debug ]----------"
	@cd "Matrix_s" && "$(MAKE)" -f  "Matrix_s.mk" clean
