.PHONY: clean All

All:
	@echo "----------Building project:[ Matrix - Debug ]----------"
	@cd "Matrix" && "$(MAKE)" -f  "Matrix.mk"
clean:
	@echo "----------Cleaning project:[ Matrix - Debug ]----------"
	@cd "Matrix" && "$(MAKE)" -f  "Matrix.mk" clean
