.PHONY: clean All

All:
	@echo "----------Building project:[ ex_23 - Debug ]----------"
	@cd "ex_23" && "$(MAKE)" -f  "ex_23.mk"
clean:
	@echo "----------Cleaning project:[ ex_23 - Debug ]----------"
	@cd "ex_23" && "$(MAKE)" -f  "ex_23.mk" clean
