.PHONY: clean All

All:
	@echo "----------Building project:[ ex_27 - Debug ]----------"
	@cd "ex_27" && "$(MAKE)" -f  "ex_27.mk"
clean:
	@echo "----------Cleaning project:[ ex_27 - Debug ]----------"
	@cd "ex_27" && "$(MAKE)" -f  "ex_27.mk" clean
