.PHONY: clean All

All:
	@echo "----------Building project:[ ex_12 - Debug ]----------"
	@cd "ex_12" && "$(MAKE)" -f  "ex_12.mk"
clean:
	@echo "----------Cleaning project:[ ex_12 - Debug ]----------"
	@cd "ex_12" && "$(MAKE)" -f  "ex_12.mk" clean
