.PHONY: clean All

All:
	@echo "----------Building project:[ ex_13 - Debug ]----------"
	@cd "ex_13" && "$(MAKE)" -f  "ex_13.mk"
clean:
	@echo "----------Cleaning project:[ ex_13 - Debug ]----------"
	@cd "ex_13" && "$(MAKE)" -f  "ex_13.mk" clean
